### ISSUE TITLE
ENTRYPOINT or CMD?

### ISSUE THREAD

**Issue by DylanSale** [ohjames/smell-baron#1]
In the README.md, should the usage be changed from:

> CMD ["/bin/smell-baron", "/bin/node", "app.js" ]

to

> ENTRYPOINT ["/bin/smell-baron"]

That way, dockerfiles that extend of the current image will not have to worry about adding smell-baron to the CMD.

**Comment by insidewhy** [comment]
Fixed!

Thank you noble Sir Dylan, your contribution is appreciated verily and I would like to award you this noble title of:

"His Royal Steward of Looking Vacantly out of the window at Kittens Playing whilst staying away from Neighbour's bins"
