### ISSUE TITLE
Running in Minimal Container

### ISSUE THREAD

**Issue by ghost** [ohjames/smell-baron#2]
```
$ docker run --rm -it alpine sh
/ # apk add -U openssl file
fetch http://dl-4.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
(1/2) Installing file (5.22-r0)
(2/2) Installing openssl (1.0.2d-r0)
Executing busybox-1.23.2-r0.trigger
OK: 9 MiB in 17 packages
/ # wget https://github.com/ohjames/smell-baron/releases/download/v0.1.0/smell-baron
Connecting to github.com (192.30.252.128:443)
Connecting to s3.amazonaws.com (54.231.2.64:443)
smell-baron          100% |***************************************************************************************************************|  9264   0:00:00 ETA
/ # chmod +x smell-baron 
/ # ./smell-baron 
sh: ./smell-baron: not found
/ # file smell-baron 
smell-baron: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.9, not stripped
/ # ldd smell-baron 
    /lib64/ld-linux-x86-64.so.2 (0x7efd9b219000)
    libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7efd9b219000)
```

Problem is the binary is compiled with dynamic linking to glibc while containers such as Alpine use musl. Recompiling with static linking fixes the problem.

```
$ gcc -Wall -std=c99 -s -static -Wl,--build-id=none -DNDEBUG -O3 main.c -o smell-baron
$ file smell-baron
smell-baron: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 2.6.32, stripped
```

**Comment by insidewhy** [comment]
That would work but it's better if you can avoid statically linking glibc given how easy docker makes it to build things on multiple distributions, thanks for opening this bug :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick: :baby_chick:

**Comment by insidewhy** [comment]
Added build stuff for alpine: 950a2e7

Unfortunately won't build against musl:

```
gcc -Wall -std=c99 -DNDEBUG -O3 main.c -o smell-baron
main.c:2:23: fatal error: sys/types.h: No such file or directory
 #include <sys/types.h>
                       ^
compilation terminated.
Makefile:12: recipe for target 'smell-baron' failed
make: *** [smell-baron] Error 1
The command '/bin/sh -c cd smell-baron && make release' returned a non-zero code: 2
```

google leads me to: https://github.com/acassen/keepalived/issues/158

Can try conditionally including `sys/types.h` maybe, will look at it more later. You could check it out too now if you want, the build scripts and instructions to build on alpine are in that commit.

**Comment by ghost** [comment]
```
$ docker run --rm -it alpine sh
/tmp # apk add -qU g++ make git
/tmp # git clone -q https://github.com/ohjames/smell-baron.git
remote: Counting objects: 64, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 64 (delta 0), reused 0 (delta 0), pack-reused 57
Unpacking objects: 100% (64/64), done.
/tmp # cd smell-baron
/tmp/smell-baron # make smell-baron
gcc -Wall -std=c99 -DNDEBUG -O3 main.c -o smell-baron
/tmp/smell-baron # ldd smell-baron
    /lib/ld-musl-x86_64.so.1 (0x7f46c4492000)
    libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f46c4492000)
```

**Comment by ohjames** [comment]
That wasn't enoug

**Comment by insidewhy** [comment]
I needed to install musl-dev also, fixed the build in 412c26ba450b5ea38b9193a8dbe85b6a443bcf58 :baby_chick:

**Comment by insidewhy** [comment]
I guess your g++ package also brought in musl-dev, however g++ isn't necessary to build smell-baron.

**Comment by ghost** [comment]
I know this is not written in C++; that was just out of convience and habbit. Something else I've encounted is that smell-baron is unable to kill `php-fpm` even enough it doesn't require special signals or anything else AFAIK.

```
$ docker run --rm -it -p 80:80 usertaken/cryptoglance sh
/tmp # apk add -qU gcc musl-dev git
/tmp # git clone -q https://github.com/ohjames/smell-baron.git
remote: Counting objects: 71, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 71 (delta 1), reused 0 (delta 0), pack-reused 64
Unpacking objects: 100% (71/71), done.
/tmp # cd smell-baron/
/tmp/smell-baron # gcc -Wall -std=c99 -DNDEBUG -O3 main.c -o smell-baron
/tmp/smell-baron # ./smell-baron nginx -g "daemon off;" --- php-fpm -F
[19-Jul-2015 00:53:49] NOTICE: fpm is running, pid 23
[19-Jul-2015 00:53:49] NOTICE: ready to handle connections
^C^C^C/tmp/smell-baron # ps
PID   USER     TIME   COMMAND
    1 root       0:00 sh
   23 root       0:00 php-fpm: master process (/etc/php/php-fpm.conf)
   26 nobody     0:00 php-fpm: pool www
   27 nobody     0:00 php-fpm: pool www
   28 root       0:00 ps
```

**Comment by insidewhy** [comment]
@UserTaken only the process with PID 1 can adopt orphaned child processes, in your example there your `sh` process is running as PID 1 and adopts the orphaned php-fpm process. So when `smell-baron` terminates it is expected that it cannot kill the daemonised/orphaned `php-fqm`. You could verify this with `ps -eo "%p %P %y %x %c"` which will show the parent PID in the second column.

**Comment by insidewhy** [comment]
That's just a guess though, I don't use PHP so I don't know how the php-fqm process works but you can verify yourself with the `ps` command I gave there. Even though you used the -F flag the foreground flag may only apply to the parent process and might not guarantee spawned children don't get orphaned. In general it's worth bearing in mind that `smell-baron` should be PID 1 anyway. You could get more info on the console if you compiled `smell-baron` in debug mode.
