### ISSUE TITLE
What license is this under?!

### ISSUE THREAD

**Issue by notriddle** [ohjames/smell-baron#5]
I can't find a copyright notice. Without one, our legal department will eat us alive.

**Comment by notriddle** [comment]
You'll need to ask all previous contributers permission to relicense this, whatever you use. I recommend the Apache license, but since we're not doing anything that would prevent our users from replacing stuff, the GPL is perfectly acceptable.

**Comment by DylanSale** [comment]
I'm fine with Apache

On Tue, 5 Jan 2016, 07:10 Michael Howell notifications@github.com wrote:

> You'll need to ask all previous contributers permission to relicense this,
> whatever you use. I recommend the Apache license, but since we're not doing
> anything that would prevent our users from replacing stuff, the GPL is
> perfectly acceptable.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ohjames/smell-baron/issues/5#issuecomment-168800591.
> 
> ## 
> 
> Dylan Sale

CTO - Enabled
enabled.com.au
08 8272 6658

**Comment by insidewhy** [comment]
@DylanSale Apache seems like a good idea, @clkao you okay with apache license for your contribution?

**Comment by clkao** [comment]
certainly.

**Comment by insidewhy** [comment]
@clkao @DylanSale Thanks for responding so quickly.
@notriddle Thanks for pointing out my oversite, I've added the license now.

**Comment by notriddle** [comment]
Thanks!
