### ISSUE TITLE
A delay of 10s while stopping the container

### ISSUE THREAD

**Issue by sudhaker** [ohjames/smell-baron#7]
This is the 'entrypoint.sh' for my alpine container (nginx + php; all-in-one container)

exec /bin/smell-baron \
**-f nginx -g "daemon off;"** \
"---" \
**php-fpm**

Both processes exits immediately if I issue a SIGTERM from inside the container but a "docker stop" is only killing nginx and php-fpm continues to run until 10s is elapsed and SIGKILL 

Everything working great and I love the tiny init binary but a delay of 10s while stopping the container is bothering me. Is this by design or I'm missing something?

> while true; do date; sudo docker exec alpined-nginx-php /bin/ps; sleep 1; done

```
Mon Jun 13 08:32:28 EDT 2016
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/smell-baron -f nginx -g daemon off; --- php-fpm
    7 root       0:00 nginx: master process nginx -g daemon off;
    8 root       0:00 php-fpm: master process (/etc/php/php-fpm.conf)
    9 nobody     0:00 nginx: worker process
   10 nobody     0:00 nginx: worker process
   11 nobody     0:00 php-fpm: pool www
   12 nobody     0:00 php-fpm: pool www
   96 root       0:00 /bin/ps
Mon Jun 13 08:32:29 EDT 2016
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/smell-baron -f nginx -g daemon off; --- php-fpm
    8 root       0:00 php-fpm: master process (/etc/php/php-fpm.conf)
   11 nobody     0:00 php-fpm: pool www
   12 nobody     0:00 php-fpm: pool www
  102 root       0:00 /bin/ps
Mon Jun 13 08:32:30 EDT 2016
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/smell-baron -f nginx -g daemon off; --- php-fpm
    8 root       0:00 php-fpm: master process (/etc/php/php-fpm.conf)
   11 nobody     0:00 php-fpm: pool www
   12 nobody     0:00 php-fpm: pool www
  107 root       0:00 /bin/ps

```

**Comment by nordluf** [comment]
It looks, like the problem is in entrypoint.sh itself. Change your Dockerfile 
ENTRYPOINT ["/bin/smell-baron","-f","nginx", "-g","daemon off;",""---"","php-fpm"]

**Comment by insidewhy** [comment]
@nordluf is correct, then ten second delay is nothing to do with smell-baron.

**Comment by insidewhy** [comment]
BTW I would just set entrypoint to the smell-baron -f bit and use `cmd` for the rest.

**Comment by sudhaker** [comment]
Following didn't make any difference

`ENTRYPOINT ["/bin/smell-baron", "-f", "nginx", "-g", "daemon off;", "---", "php-fpm"]`

And my gut feeling tells me that setting "entrypoint to the smell-baron -f bit and use cmd for the rest" will have similar result.

Seems the initial SIGTERM is not propagated to "php-fpm", which is the root cause here; and after 10s Docker issues another SIGKILL to all processes inside container (default behavior) hence the delay.

Ref: https://www.ctl.io/developers/blog/post/gracefully-stopping-docker-containers/

**Comment by sudhaker** [comment]
You can see below that "php-fpm" is behaving correctly and exits immediately with SIGTERM; something is missing in signal wiring through "smell-baron".

```
$ docker exec alpined-nginx-php /bin/ps && docker exec alpined-nginx-php /bin/kill 8 && docker exec alpined-nginx-php /bin/ps
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/smell-baron -f nginx -g daemon off; --- php-fpm
    7 root       0:00 nginx: master process nginx -g daemon off;
    8 root       0:00 php-fpm: master process (/etc/php/php-fpm.conf)
    9 nobody     0:00 nginx: worker process
   10 nobody     0:00 nginx: worker process
   11 nobody     0:00 php-fpm: pool www
   12 nobody     0:00 php-fpm: pool www
   18 root       0:00 /bin/ps
PID   USER     TIME   COMMAND
    1 root       0:00 /bin/smell-baron -f nginx -g daemon off; --- php-fpm
    7 root       0:00 nginx: master process nginx -g daemon off;
    9 nobody     0:00 nginx: worker process
   10 nobody     0:00 nginx: worker process
   30 root       0:00 /bin/ps
```

Please consider re-opening the ticket.

**Comment by insidewhy** [comment]
Is that command you pasted the one you actually used?

```
% kill -8
kill: not enough arguments
```

**Comment by insidewhy** [comment]
Oops `kill 8` not `kill -8`

**Comment by insidewhy** [comment]
I don't see what `smell-baron` is doing wrong here, when `php-fqm` is killed it seems that `nginx` just takes 10 seconds to exit. If you want everything to terminate as soon as php-fqm is killed then you should use `-f` before `php-fqm` rather than `nginx`

**Comment by insidewhy** [comment]
So your entrypoint would be:

```
ENTRYPOINT ["/bin/smell-baron", "-f", "php-fpm", "---", "nginx", "-g", "daemon off;"]
```

The default behaviour is not "when any watched command is killed, kill the rest" but "wait for all the watched commands to exit", which can be changed with the `-f` flag.

**Comment by sudhaker** [comment]
Do you think "smell-baron" is passing SIGTERM to nginx & php-fpm both when "docker stop" is issues?

I tried to kill both processes with SIGTERM and they exit almost immediately. So I'm guess that somehow "smell-baron" is not relaying the signals (which is the main issue here); and container only exits after 10s (that's when docker sends SIGKILL and force kill everything).

**Comment by sudhaker** [comment]
-f is adding extra confusion here ... the following also takes 10s

`ENTRYPOINT ["/bin/smell-baron", "nginx", "-g", "daemon off;", "---", "php-fpm"]
`

```
date; docker stop alpined-nginx-php; date
Mon Jun 13 13:56:49 EDT 2016
alpined-nginx-php
Mon Jun 13 13:56:59 EDT 2016
```

**Comment by insidewhy** [comment]
Are you sure nginx isn't just taking really long to stop?

**Comment by insidewhy** [comment]
When I run `smell-baron sleep 10` and then ctrl-C the sleep gets killed before the timeout.

**Comment by sudhaker** [comment]
Somehow SIGTERM is not reaching "php-fpm" process (PID 8).

Let me upload the project on github and share.

**Comment by insidewhy** [comment]
```
./smell-baron.debug sleep 1000 --- sleep 2000
got signal 2
waitpid interrupted by signal
all processes exited cleanly
```

I sent SIGTERM to smell-baron in another terminal before `got signal 2` appeared on stdout.

**Comment by sudhaker** [comment]
ENTRYPOINT ["nginx", "-g", "daemon off;"] <- exits immediately when container is stopped
ENTRYPOINT ["/bin/smell-baron", "nginx", "-g", "daemon off;"] <- exits immediately when container is stopped

So "smell-baron" is working as expected.

ENTRYPOINT ["php-fpm"] <- exits immediately when container is stopped

ENTRYPOINT ["/bin/smell-baron", "php-fpm"] <- 10s delay when container is stopped
ENTRYPOINT ["/bin/sh", "-c", "php-fpm"] <- 10s delay when container is stopped

Something weird with the way "php-fpm" handles the signal. Closing the ticket.

**Comment by nordluf** [comment]
Last one is expected. 
But previous looks like the easiest way to reproduce the error. This behavior looks wrong, at least for me

**Comment by sudhaker** [comment]
Command "docker stop" responds immediately if I simply wrap php-fpm with a shell-script.

`ENTRYPOINT ["/bin/smell-baron", "/scripts/php-fpm.sh"]`

And here is the "php-fpm.sh"

```
#! /bin/sh

my_term() { 
  echo "Caught SIGTERM signal!" 
  kill -TERM "$child" 2>/dev/null
}

trap my_term SIGTERM

php-fpm &

child=$! 
wait "$child"
```

**Comment by insidewhy** [comment]
If you run php-fpm by itself does it detach from the shell?

**Comment by insidewhy** [comment]
Looks to me like `php-fpm -F` would be more safe.

**Comment by sudhaker** [comment]
Project @ https://github.com/alpined/alpined-nginx-php

I already have "daemonize = no" in the php-fpm.conf

FPM config @ https://github.com/alpined/alpined-nginx-php/blob/master/rootfs/etc/php5/php-fpm.conf

**Comment by insidewhy** [comment]
@sudhaker I know why this is now, when you used `ps` it would have been good to use flags such as `-efj` to ensure the PGID is shown. In this case you probably would have seen that the processes that the php-fpm process spawned are in a different process group. Given that it puts them in a different PGID it should also take responsibility to shut them down with it, so I guess you could say php-fpm is misbehaving and it might be worth raising a bug against them. Then again maybe they have a good reason for acting the way they do. I guess it could be worthwhile adding a flag to `smell-baron` to tell it to kill all processes in the container (not those in the same PGID) for situations like this.

**Comment by sudhaker** [comment]
Great job James. It was really bothering me for past many days.

Here is the equivalent command for alpine-linux; we can clearly see the misbehaving php-fpm family of processes with different PGID.

In example below (output from dumb-init based container), we only need to kill PID 6,8,10 (with PPID = 1); and 8 should take care of killing 11,12 & 10 should take care of killing 13,14

Can we find PIDs by PPID? That'll be cleaner approach than signaling all processes.

```
[root@my-centos ~]# docker exec my-nginx /bin/ps -o pid,ppid,pgid,user,group,comm,args
PID   PPID  PGID  USER     GROUP    COMMAND          COMMAND
    1     0     1 root     root     dumb-init        /sbin/dumb-init /bin/sh /scripts/run.sh
    6     1     6 root     root     crond            /usr/sbin/crond -f
    8     1     8 root     root     php-fpm          php-fpm: master process (/etc/php5/php-fpm.conf)
   10     1     6 root     root     nginx            nginx: master process nginx -g daemon off;
   11     8     8 nobody   nobody   php-fpm          php-fpm: pool www
   12     8     8 nobody   nobody   php-fpm          php-fpm: pool www
   13    10     6 nobody   nobody   nginx            nginx: worker process
   14    10     6 nobody   nobody   nginx            nginx: worker process

```

I was struggling (ref - https://github.com/alpined/nginx-php-smell) when added shell script as a pre-launch hook (couldn't avoid having /bin/sh as PID1) and switched to yelp's dumb-init which seems to work for my use-case. ref - https://github.com/alpined/nginx-php ; not very happy with this implementation but I do prefer it over s6 or anything else because it's light (like smell-baron).

This could be another feature request for "smell-baron" :-)
`./smell-baron -w cmd1 --- cmd2 --- cmd3`
should wait for cmd1 to finish and then launch cmd2 & cmd3 in regular supervised mode.

**Comment by insidewhy** [comment]
Maybe `./smell-baron bash -c 'cmd1 && cmd2 ; exec cmd3`, the `exec` will replace the bash process (and hopefully not kill cmd2 in the process).

**Comment by insidewhy** [comment]
OK the working command is `bash -c 'cmd2 && cmd2 & exec cmd3'`

**Comment by insidewhy** [comment]
I've added the `-a` flag to deal with this, testing it now.

**Comment by insidewhy** [comment]
Fixed! https://github.com/ohjames/smell-baron/releases/tag/v0.3.1

**Comment by insidewhy** [comment]
> This could be another feature request for "smell-baron" :-)
> ./smell-baron -w cmd1 --- cmd2 --- cmd3
> should wait for cmd1 to finish and then launch cmd2 & cmd3 in regular supervised mode.

I've added the `-c` flag now which acts like your `-w`, it's in the README.

**Comment by sudhaker** [comment]
Super awesome!

**Comment by insidewhy** [comment]
You still using dumb-init or switched back to smell-baron? Any features dumb-init has that you think smell-baron should have?

**Comment by sudhaker** [comment]
Will switch back as it's the best option available now ;-)

**Comment by insidewhy** [comment]
@sudhaker haha that's great to hear. BTW, love the new profile picture, very handsome.

**Comment by sudhaker** [comment]
The smell-baron is my official 'tiny init' ;-) Thanks my friend.

https://hub.docker.com/r/alpined/jupyter-py3-sh/
https://hub.docker.com/r/alpined/nginx-php/

**Comment by huguesalary** [comment]
Stumbled upon this, a year later, but just in case you're still wondering where this 10s delay comes from, I'm wondering if your PHP-FPM config comes with `process_control_timeout = 10s` in `php-fpm.conf` which instructs the php-fpm master process to wait 10seconds before sending TERM to its child.

**Comment by sudhaker** [comment]
Nah - it was Docker who was doing force-kill after 10s. We have the root-cause identified by James in his July-1st comment.

**Comment by insidewhy** [comment]
@sudhaker but @huguesalary has explained why php-fpm failed to kill its child processes. Thanks!
